### PR TITLE
fix duplication of class names

### PR DESCRIPTION
**Pull request by varunmamtora06**
- I have fixed the duplication issue buy adding ```unique = True``` property to the classroom model's  classname entity.

- Also I have updated the views file and upload.html template to give the message info stating "classname already exists" if classname is duplicated.

### CODE REVIEW

**Review by varunmamtora06 — COMMENTED** [review]
reviewed changes

**Comment by Logan1x** [comment]
Varun, we have bit of confusion on this issue, we'll reach out to you soon.

**Comment by parthpandyappp** [comment]
Thanks @varunmamtora06 , actually we're confused with some changes we decided before and thinking those might not needed to us aanymore. The decision is still pending but your contributions are merged in a different branch.
Thanks, Happy Hacking! :+1:

**Comment by varunmamtora06** [comment]
> Thanks @varunmamtora06 , actually we're confused with some changes we decided before and thinking those might not needed to us aanymore. The decision is still pending but your contributions are merged in a different branch.
> Thanks, Happy Hacking! 👍

ThankYou @parthpandyappp Happy Hacking to you too!

**Pull request merged**
